### PR TITLE
Add unlocked Plasma Vaults

### PR DESCRIPTION
**Pull request by nl6720**

### CODE REVIEW

**Comment by rubo77** [comment]
wouldn't you backup those encrypted folders?

Or is it not possible to copy the folder to a new location and decrypt it there?

**Comment by nl6720** [comment]
The encrypted vaults are stored in `~/.local/share/plasma-vault/`. Those are not excluded and it's possible to decrypt them from the copies.
The `~/Vaults/` directory, that I want to add, is the place where the unlocked/decrypted vaults are mounted. Typically there is nothing in the  subdirectories of `~/Vaults/` unless a vault is open, but it's safer to skip the directory to prevent accidentally backing up the decrypted files.

**Comment by rubo77** [comment]
maybe backing up the decrypted files is what a user may want to do.

So maybe we should add it commented out, with an explanation, that, if you don't want to backup currently mounted vaults, you have tu uncemment the line

**Comment by nl6720** [comment]
As you wish.

**Pull request merged**
