### PR TITLE
Update rsync-homedir-excludes.txt

### PR DESCRIPTION
**Pull request by rafaeln**
Rsync manual

> if the pattern starts with a / then it is anchored to a particular spot in the hierarchy of files, otherwise it is matched
> against the end of the pathname. This is similar to a leading ^ in regular expressions. Thus "/foo" would match a name of "foo"
> at either the "root of the transfer" (for a global rule) or in the merge-file’s directory (for a per-directory rule).

### CODE REVIEW

**Comment by rubo77** [comment]
Its a good hint, but I wouldn't put it in front of every line

**Comment by rafaeln** [comment]
I don't know the possibility of that coming back to bite you, but if you don't put / in front of every line, and then happen to have an embedded folder in the source tree that endš the same as one of the lines, then that folder is going to be unexpectedly excluded from the backup.

**Comment by rubo77** [comment]
Sure, i am aware of that, but for example popcorntime folders should be excluded, no matter where.
And folders starring with a dot, that are not in the root of home are 100% copies of such folders so these should be excluded too.

For all other folders you are right, so this has to be changed

**Comment by rafaeln** [comment]
Oh, I see. That is true.

**Comment by rubo77** [comment]
I think now I added a slash to all folders, that could occur somewhere else where you don't want to exclude them

**Pull request closed without merging**
