### PR TITLE
Add keychain session specific dir

### PR DESCRIPTION
**Pull request by mikkoi**
http://www.funtoo.org/Keychain

Signed-off-by: Mikko Johannes Koivunalho mikko.koivunalho@iki.fi

### CODE REVIEW

**Comment by rubo77** [comment]
can you explain, why this folder is obsolute?

**Comment by mikkoi** [comment]
What do you mean "absolute" in this case?

Normally there is only one .keychain directory and it is in user's home directory. Its content is files that different shells can source. Funtoo Keychain is a frontend for ssh-agent and gpg-agent that make the keys available in all sessions.
$ ll ~/.keychain/
-rw------- 1 \* \* \* 112 Apr 21 06:36 _-debian01-sh
-rw------- 1 \* \* \*  82 Apr 21 06:36 *-debian01-csh
-rw------- 1 \* \* \* 132 Apr 21 06:36 *-debian01-fish
$ cat ~/.keychain/_-debian01-sh
SSH_AUTH_SOCK=/tmp/ssh-5nysmdg85DuP/agent.7434; export SSH_AUTH_SOCK;
SSH_AGENT_PID=7481; export SSH_AGENT_PID;

**Comment by rubo77** [comment]
Ok, never used that, and isn't it `~/.ssh/.keychain` sometimes (like in the dokumentation)?

**Comment by mikkoi** [comment]
That funny. The docs in http://www.funtoo.org/Keychain do indeed mention "~/.ssh/.keychain", not "~/.keychain". Must be old info. But the man page says:

```
    --dir dirname
    Keychain will use dirname rather than $HOME/.keychain
```

**Comment by rubo77** [comment]
OK, but you should add a slash at the start otherwise all folders somewhere else, also named ".keychain" would be excluded

**Comment by mikkoi** [comment]
Would that not throw some programs off the track? _/.keychain_ would be ok in _.gitignore_ but that's about it?

**Comment by rubo77** [comment]
This is about an exclude list for rsync so it must be like this with aa slash at the start

**Comment by mikkoi** [comment]
Sorry. Of course, that's right. Fixed, I think.

**Pull request merged**
