### PR TITLE
Update rsync-homedir-excludes.txt

### PR DESCRIPTION
**Pull request by qwertygc**
Add R, Rstudio,  Qgis, audacity, LinuxMint

### CODE REVIEW

**Comment by rubo77** [comment]
wouldn't the `R` entry exclude all files containing a capital R?

**Comment by qwertygc** [comment]
No R is the name of the dir for "R" stats language

**Comment by rubo77** [comment]
But if you add a folder "R" then a similar Folder somewhere else would be excluded also. "R" is occurring more often than just in the language R.

and another thing: 
you added your files in the (commented out) section "directories, probably not worth a backup" and there in the "games" section.

**Comment by qwertygc** [comment]
Ok. How to exclude only R dir ?
ok what is the good section for me?

**Comment by rubo77** [comment]
Add a new section.

And don't put # before each line or they are ignored.


Please test this by adding some test folders before you backup your home dir
Maybe add

    /R

Then only the root folder R will be ignored

**Comment by rubo77** [comment]
I think some people want to backup those folders

**Pull request closed without merging**
